### ISSUE TITLE
4월 3일 FE 요청건

### ISSUE THREAD

**Issue by JaeHackJang** [FastCampus-MoReturn/final-project-Be#21]
## Title

4월 3일 FE 요청건 

#### PDF 파싱데이터 추가 요청건
 - 대지권비율
 - 현재 매물의 층

#### PDF 파싱 데이터 수정 요청건
 - 공유자일경우 지분 비율 숫자로만 제공 100% 가 1 기준 0.5 0.5 이런식으로
 - 전용면적은 숫자로만

## Tasks

- [x] PDF 파싱 로직 추가 (대지권비율, 현재매물의층)
- [x] PDF 파싱 기존 로직 수정(전용면적 부분, 소유자 지분 부분)
- [x] 아파트 단지정보 오픈 API 체크하여 전용면적 리스트 가능여부 체킹
- [x] 가능하면 코드 구현하여 반환값 만들기 결과 도출

**Comment by JaeHackJang** [comment]
해당아파트의 전용면적을 제공하는 api는 없는것으로 확인..
